name: uq

channels:
  - defaults
  - conda-forge
  - janosg

dependencies:
- python=3.6
- pip
- numpy
- pandas=0.24
- jupyterlab
- matplotlib
- seaborn
- scipy
- estimagic=0.0.8
- pip:
  - chaospy
  #- respy; commented out b/c respy version from develop branch needed.